source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

def all_pods
  pod 'AEXML'
  # pod 'SwiftSVG'
  pod 'Alamofire'
  pod 'Cartography'
  #pod 'JAMSVGImage'
  
end

target 'ITTTI' do
  all_pods
  
end

target 'ITTTITests' do
  all_pods
  
end
